name: Build and deploy Node.js app to Azure Web App - JobPortalOfficial

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r backend.zip backend/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'JobPortalOfficial'
          package: ${{ github.workspace }}/backend.zip
